package com.talkdesk.tag.reference.user.mapper;

import com.talkdesk.tag.reference.user.entity.User;
import com.talkdesk.tag.reference.user.model.UserCreate;
import com.talkdesk.tag.reference.user.model.UserRead;
import com.talkdesk.tag.reference.user.model.UserUpdate;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;

/**
 * This is a MapStruct mapper, used to convert between objects. The implementatio code is generated by an annotation
 * processor.
 *
 * Please refer to the MapStruct documentation: https://mapstruct.org/documentation.
 *
 * MapStruct was choosen because it seems to be one of the mapping libraries with best performance:
 * https://www.baeldung.com/java-performance-mapping-frameworks
 */
@Mapper(componentModel = "cdi")
public interface UserMapper {
    UserRead toUserRead(User user);

    User toUser(UserCreate userCreate);

    User toUser(UserUpdate userUpdate);

    User toUser(User source, @MappingTarget User target);

    UserUpdate toUserUpdate(UserRead userRead);
}
